FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src /app/src
RUN mvn clean package -DskipTests
FROM eclipse-temurin:24-alpine
WORKDIR /app
COPY --from=build /app/target/DockerApp.jar /app/DockerApp.jar
EXPOSE 8080
CMD ["java", "-jar", "DockerApp.jar"]